### ISSUE TITLE
[BUG] chardonnay-6.3-unstable 64bit cannot open executables

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [bottlesdevs/wine#15]
**Describe the bug**
The 64bit version of the chardonnay-6.3-unstable runner cannot run any exe files or open winecfg. The 32bit version works fine.

**Installation**
 - Method: Bottles Flatpak
 - Bottles Version 3.0.7

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a bottle with the gaming prefix.
2. Click on the hamburger icon.
3. Click on 'Preferences'.
4. Scroll down to 'Runners'.
5. Install the 'chardonnay-6.3-unstable' runner.
6. Close the preferences window.
7. Go to the main screen.
8. Click on the created bottles
9. Click on 'Preferences' in the header bar.
10. Scroll to 'System'
11. Click on 'Runner' (not the cog wheel).
12. Select 'chardonnay-6.3-x86_64'.
13. Click on 'Bottle' in the header bar.
14. Scroll to 'Utilities'.

Winecfg Steps
15.1. Click on 'Wine Config'
16.1. Winecfg does not open.

Exe Steps
15.2. Click on 'Run.exe'.
16.2. Choose an exe file.
17.2 The exe should be run but doesn't.

**Expected behaviour**
winecfg should open, when clicked. The exe should be executed, when chosen.

**Desktop:**
 - OS: Fedora
 - Version 33

**Comment by mirkobrombin** [comment]
Fixed

**Comment by Sebastian-Hirsch** [comment]
The issue is still there with chardonnay-6.4-unstable and the reproduction steps are all the same. I used bottles version 3.0.9.

**Comment by mirkobrombin** [comment]
There seems to be a regression

**Comment by mirkobrombin** [comment]
Build started https://github.com/bottlesdevs/wine/actions/runs/648464640

**Comment by mirkobrombin** [comment]
Fixed on latest build

**Comment by Sebastian-Hirsch** [comment]
When trying to download chardonnay-6.4-unstable in bottles it tells me, that the download is corrupted.

**Comment by mirkobrombin** [comment]
GitHub cache takes some time to expire. It may not yet see the new checksum file for the check.

**Comment by Sebastian-Hirsch** [comment]
Now the new version downloaded and installed properly, the issue still persists. Can I help with some kind of logs to fix this issue? Chardonnay 6.0 works fine in this regard.

**Comment by Sebastian-Hirsch** [comment]
Okay, bottles now has 3 versions of 6.4. the one marked as chardonnay-6.4-unstable works, the others not.

![Bildschirmfoto von 2021-03-14 13-23-00](https://user-images.githubusercontent.com/41188546/111068295-87b45480-84c8-11eb-8e98-6566c1aad854.png)

**Comment by Sebastian-Hirsch** [comment]
I have removed bottles with all its configs and sub directories and reinstalled it. Now it seems to work better and the list of available runners is not broken anymore. But trying to launch the game I installed ends with a crash. The game runs fine with the wine version from the fedora repository.
![Bildschirmfoto von 2021-03-14 13-46-04](https://user-images.githubusercontent.com/41188546/111069116-dfa08a80-84cb-11eb-9d7c-44f5e6e93632.png)

**Comment by mirkobrombin** [comment]
I can get the same warning with unstable but it is unstable so I will wait for the next build

**Comment by Sebastian-Hirsch** [comment]
The message in the screenshot is not a warning but a crash. it says that the program crashed and that winedbg could not be started. As this also happens with chardonnay stable, it is not a specific problem of the unstable version. As this diverges from the issue described in the first message, should I open a new report and we close this one?

**Comment by Sebastian-Hirsch** [comment]
I could now make out the problem. Enabling DXVK is the culprit. Disabling the DXVK option launches my game. As I use DXVK with the wine version from the fedora repo, this seems to be a bottles or chardonnay bug.
